version: '3.8'
services:
  derper:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DERP_VERSION: latest  # Set the DERP version here
    environment:
      DERP_DOMAIN: "tailscale-nguyentn.duckdns.org"          # Set your hostname
      DERP_CERT_MODE: "letsencrypt"            # Certificate mode
      DERP_CERT_DIR: "/app/certs"             # Directory for certificates
      DERP_ADDR: ":443"                        # Address to listen on
      DERP_STUN: "true"                        # Enable STUN
      DERP_STUN_PORT: "3478"                   # STUN port
      DERP_HTTP_PORT: "80"                     # HTTP port
      DERP_VERIFY_CLIENTS: "false"            # Verify clients
      DERP_VERIFY_CLIENT_URL: ""              # URL for client verification
    ports:
      - "80:80"   # Map HTTP port
      - "443:443" # Map HTTPS port
      - "3478:3478/udp" # Map STUN port (UDP)
    volumes:
      - /certs:/app/certs   # Persist certificate directory
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
  # static-website:
  #   image: nginx:latest
  #   container_name: static_website
  #   volumes:
  #     - ./static-site:/usr/share/nginx/html   # Mount your static website files
  #   ports:
  #     - "8080:80"   # Expose HTTP on a different port (optional)
  #     - "8443:443"  # Expose HTTPS on a different port (optional)
  #   restart: unless-stopped
